{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "e5856e6e_48c92280",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 10,
      "author": {
        "id": 1018108
      },
      "writtenOn": "2022-04-21T13:13:33Z",
      "side": 1,
      "message": "I think there is a problem even when throwing out of the method. I\u0027ll post an example on the bug 229706824.",
      "range": {
        "startLine": 10,
        "startChar": 39,
        "endLine": 10,
        "endChar": 65
      },
      "revId": "2c70f27682ed3756af399cf5da529fb70c5e1a1d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "14190a66_cf49441b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1889741
      },
      "writtenOn": "2022-04-20T12:38:10Z",
      "side": 1,
      "message": "Vladimir PTAL",
      "revId": "2c70f27682ed3756af399cf5da529fb70c5e1a1d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}