{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "392a8060_89566020",
        "filename": "tools/run-libcore-tests.py",
        "patchSetId": 2
      },
      "lineNbr": 261,
      "author": {
        "id": 1065473
      },
      "writtenOn": "2022-06-26T09:15:24Z",
      "side": 1,
      "message": "There is \"_\" in the name, but it should have been \"#\"",
      "revId": "6f82e430d166cb2178047af690713ebe2f6342ea",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}